services:
  test:
    build:
      context: ..
      dockerfile: git-warp/Dockerfile
    environment:
      - GIT_STUNTS_DOCKER=1

  benchmark:
    build:
      context: ..
      dockerfile: git-warp/Dockerfile
    volumes:
      - ./benchmarks:/app/benchmarks
    environment:
      - GIT_STUNTS_DOCKER=1
    command: ["node", "benchmarks/benchmark.js"]
